server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myrbac?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    mode: HTML5

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.qf.pojo






